Integration with dandelion
icbi-lab/scirpy pull request #240
Opened 2021-02-09 12:49 UTC by zktuong

Some initial code that should work with dandelion to convert between the two instances  from https://github.com/zktuong/dandelion/pull/49 onwards.

Still need to work in the extra bits on fully initialized scirpy and dandelion objects.

2021-02-10 08:04 UTC, grst requested changes
Added some comments, I hope I'm not too nitpicky ;) 

Eventually, we'll need to add tests for that as well, but you can also leave that to me.

2021-02-10 08:04 UTC, grst commented on scirpy/io/_io.py
> +def read_dandelion(Dandelion, import_all = False):
```suggestion
def read_dandelion(dandelion, import_all = False):
```

only class names should start with upper case, not instances thereof

2021-02-10 08:04 UTC, grst commented on scirpy/io/_io.py
> +    if isinstance(path, str) or isinstance(path, Path) or isinstance(path, pd.DataFrame):
```suggestion
    if isinstance(path, (str, Path, pd.DataFrame)):
```

(just found out myself that this is possible)

2021-02-10 08:05 UTC, grst commented
Ah, and you'll need to run the black formatter as well. 
The easiest way to ensure that is to use the pre commit hook - it will format on every git commit. 

To set it up, run the following commands in the root of the repository
```bash
pip install pre-commit
pre-commit install
```

2021-02-10 10:05 UTC, zktuong commented on scirpy/io/_io.py
> +                    elif all('igh' in x.lower() for x in tmp if x == x and x is not None):
it's shortcut to catch NaNs, and also because NaNs can't be lowered.

2021-02-10 10:12 UTC, zktuong commented on scirpy/io/_io.py
> +                        locus = 'TRG'
so for this, I tried to keep the loop to be similar to the airr iterator except i can't use `for row in reader:` for a pandas object (it returns the column).

`for index, row in reader.iterrows():` is the alternative which will enable that. not sure if it's possible to do a if-else for different beginnings for a for-loop?

2021-02-10 10:17 UTC, grst commented on scirpy/io/_io.py
> +                        locus = 'TRG'
in that case you can do: 

```python
if isinstance(...): 
   iterator = tmp_path.copy().iterrows()
else:
   iterator = airr.read()
   
for row in iterator: 
   ...
```

2021-02-10 10:35 UTC, zktuong commented on scirpy/io/_io.py
> +                        locus = 'TRG'
nope not working. the iterator with `iterrows()` is returning a tuple `(index, pd.Series)`.

2021-02-10 10:43 UTC, zktuong commented on scirpy/io/_io.py
> +                        locus = 'TRG'
ok i think i found a fix.

```python
if isinstance(tmp_path, pd.DataFrame):
  rows = []
  iterator = tmp_path.copy().iterrows()
  for i in iterator:
    rows.append(i[1])
else:
  rows = airr.read_rearrangement(str(tmp_path))

for row in rows:
  ...
```

2021-02-10 10:45 UTC, grst commented on scirpy/io/_io.py
> +                        locus = 'TRG'
then 
```python
idxiter, iterator = zip(*tmp_path.copy().iterrows())
```

2021-02-10 11:42 UTC, grst commented on scirpy/io/_io.py
> +                    elif all('igh' in x.lower() for x in tmp if x == x and x is not None):
best use `pd.isnull(x)` instead. 
It also covers the `None` case and is much more explicit.

2021-03-05 12:03 UTC, zktuong commented
This is almost ready for review. I'm just trying to solve some bugs with my github actions on `dandelion`'s side holding up further work; seems like the actual tests on this side are working for now, pending updates to #241, but the docs are failing - seems unrelated?.

2021-03-05 12:16 UTC, grst commented
The docs complain about something with the type annotations... don't see how this would be related since no type annotations have changed in this PR. 

I'll finally dedicate some time to scirpy next week, but I would like to  finish up #230 first, before I look into #241. 
Is this blocking anything on your side?

2021-03-05 12:18 UTC, zktuong commented
Nope all good - take your time.

2021-03-21 14:06 UTC, grst commented
This is now merged into #241. I'll keep you posted!

2021-03-21 14:06 UTC, closed without merging